model_name: klue/roberta-large
batch_size: 16
max_epoch: 6
lr_scheduler: cosine_annealing
shuffle: true
learning_rate: 2e-05
train_path: ~/dataset/train/train_a_final_seed_123.csv
dev_path: ~/dataset/train/val_a_final_seed_123.csv
test_path: ~/dataset/train/test_final.csv
predict_path: ~/dataset/test/test_data.csv
weight_decay: 0.01
warm_up_ratio: 0.1
loss_func: CE